Description of sfa1_step
Home > sfa_tk > sfa > sfa1_step.m
sfa1_step
PURPOSE
SFA1_STEP a step in the SFA1 algorithm.
SYNOPSIS
function sfa1_step(hdl, arg, step)
DESCRIPTION
 SFA1_STEP a step in the SFA1 algorithm.
   SFA1_STEP(HDL, ARG, STEPNAME)
   Do not use this function directly, use SFA_STEP instead.
   See also SFA_STEP
CROSS-REFERENCE INFORMATION
This function calls:
lcov_clear LCOV_CLEAR Delete a covariance object.
lcov_create LCOV_CREATE Create a new covariance object.
lcov_fix LCOV_FIX Fix a covariance object.
lcov_update LCOV_UPDATE Update a covariance object.
timediff TIMEDIFF Compute the derivative of a signal
This function is called by:
sfa_step SFA_STEP Update a step of the SFA algorithm.