Description of sfa_step
Home > extra > test4 > sfa_tk > sfa > sfa_step.m
sfa_step
PURPOSE
SFA_STEP Update a step of the SFA algorithm.
SYNOPSIS
function sfa_step(hdl, arg, step)
DESCRIPTION
 SFA_STEP Update a step of the SFA algorithm.
   SFA_STEP(HLD, DATA[, STEP]) updates the current step of the SFA
   algorithm. HDL is the handle of an SFA object, DATA contains a chunk of
   input data (each column a different variable).
   STEP specifies the current SFA step. If not specified, the current
   step is used. The steps must be given in the right sequence:
     for SFA1 objects:  'preprocessing', 'sfa'
     for SFA2 objects:  'preprocessing', 'expansion', 'sfa'
   Each time a new step is invoked, the previous one is closed, which
   might take some time.
   Example: suppose you have divided your training data into two chunks,
   DATA1 and DATA2. Let the number of input dimensions be N. To apply
   SFA on them write:
   hdl = sfa2_create(N,xp_dim(N))
   sfa_step(hdl, DATA1, 'preprocessing')
   sfa_step(hdl, DATA2)
   sfa_step(hdl, DATA1, 'expansion')
   sfa_step(hdl, DATA2)
   sfa_step(hdl, [], 'sfa')
   output1 = sfa_execute(hdl, DATA1)
   output2 = sfa_execute(hdl, DATA2)
   See also SFA1_CREATE, SFA2_CREATE, SFA_EXECUTE
CROSS-REFERENCE INFORMATION
This function calls:
sfa1_step SFA1_STEP a step in the SFA1 algorithm.
sfa2_step SFA2_STEP a step in the SFA2 algorithm.
This function is called by:
sfa1 SFA1 Linear Slow Feature Analysis.
sfa2 SFA2 Expanded Slow Feature Analysis.
sfa2_step SFA2_STEP a step in the SFA2 algorithm.
SOURCE CODE
function sfa_step(hdl, arg, step)
% SFA_STEP Update a step of the SFA algorithm.
%   SFA_STEP(HLD, DATA[, STEP]) updates the current step of the SFA
%   algorithm. HDL is the handle of an SFA object, DATA contains a chunk of
%   input data (each column a different variable).
%
%   STEP specifies the current SFA step. If not specified, the current
%   step is used. The steps must be given in the right sequence:
%     for SFA1 objects:  'preprocessing', 'sfa'
%     for SFA2 objects:  'preprocessing', 'expansion', 'sfa'
%   Each time a new step is invoked, the previous one is closed, which
%   might take some time.
%
%   Example: suppose you have divided your training data into two chunks,
%   DATA1 and DATA2. Let the number of input dimensions be N. To apply
%   SFA on them write:
%
%   hdl = sfa2_create(N,xp_dim(N))
%   sfa_step(hdl, DATA1, 'preprocessing')
%   sfa_step(hdl, DATA2)
%   sfa_step(hdl, DATA1, 'expansion')
%   sfa_step(hdl, DATA2)
%   sfa_step(hdl, [], 'sfa')
%   output1 = sfa_execute(hdl, DATA1)
%   output2 = sfa_execute(hdl, DATA2)
%
%   See also SFA1_CREATE, SFA2_CREATE, SFA_EXECUTE
  global SFA_STRUCTS
  if SFA_STRUCTS{hdl}.deg==1,
    sfa1_step(hdl, arg, step);
  else
    sfa2_step(hdl, arg, step);
  end