Description of sfa_clear
Home > extra > test4 > sfa_tk > sfa > sfa_clear.m
sfa_clear
PURPOSE
SFA_CLEAR Clear a SFA object.
SYNOPSIS
function sfa_clear(hdl)
DESCRIPTION
 SFA_CLEAR Clear a SFA object.
   SFA_CLEAR(HDL) clears the SFA object referenced by HDL and performs a
   PACK operation.
   See also SFA_CLEARALL
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sfa1 SFA1 Linear Slow Feature Analysis.
sfa2 SFA2 Expanded Slow Feature Analysis.
sfa2_step SFA2_STEP a step in the SFA2 algorithm.
SOURCE CODE
function sfa_clear(hdl)
% SFA_CLEAR Clear a SFA object.
%   SFA_CLEAR(HDL) clears the SFA object referenced by HDL and performs a
%   PACK operation.
%
%   See also SFA_CLEARALL
  global SFA_STRUCTS
  SFA_STRUCTS{hdl}=[];
  pack